title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-08
owner: ucsb-cs156-s25
repo_name: team02-s25-08
pull_requests: [{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-menuitemreview-editpage","number":96,"title":"Tg-menuitemreview editpage","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/96"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-MenuItemReview-indexpage","number":95,"title":"Tg menu item review indexpage","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/95"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"createpg","number":94,"title":"hs - Create Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/94"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-MenuItemReview-CreatePage","number":92,"title":"Tg-menu item review create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/92"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"placeholder-org","number":90,"title":"hs - placeholder for UCSB Organization","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/90"},{"author":{"id":"U_kgDOCM7nFQ","is_bot":false,"login":"rbuneti","name":""},"headRefName":"rb-recreq-form-component","number":85,"title":"rb - create Recreq form, add tests and add stories file","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/85"}]
