title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"
repo: ucsb-cs156-s25/team02-s25-08
owner: ucsb-cs156-s25
repo_name: team02-s25-08
pull_requests: [{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"tables","number":83,"title":"Tables","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/83"},{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-HelpRequest-FormComponent","number":82,"title":"Na help request form component for real this time hopefully","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/82"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"form0component","number":81,"title":"Form Component for UCSBOrganization plus tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/81"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"new-branch-name","number":80,"title":"hs - added js fixtures","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/80"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-Placeholders","number":78,"title":"Sz  - Articles Nav bar Placeholders","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/78"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-Table","number":77,"title":"Sz  - Add articles table","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/77"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-Component","number":76,"title":"Sz - add components for Articles","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/76"}]
