
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-08
owner: ucsb-cs156-s25
repo_name: team02-s25-08
pull_requests: [{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-HelpRequest-fixtures","number":66,"title":"NA HelpRequest fixture creation","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/66"},{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-copy-CRUD-API-files","number":65,"title":"gl - copied backend CRUD ops for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/65"},{"author":{"id":"U_kgDOB7-7uA","is_bot":false,"login":"selenazeng1","name":"Selena Zeng"},"headRefName":"sz-Articles-copy-files","number":64,"title":"sz - Copy Articles files from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/64"}]
