
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-08
owner: ucsb-cs156-s25
repo_name: team02-s25-08
pull_requests: [{"author":{"id":"U_kgDOCu9O7Q","is_bot":false,"login":"nathanalexander626","name":"Nathan Alexander"},"headRefName":"NA-team03-e2e-tests","number":131,"title":"NA Team03 E2E Tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/131"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-menuitemreview-end2end-test","number":130,"title":"Tg- MenuItemReview End to End tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/130"},{"author":{"id":"U_kgDOB0zlvA","is_bot":false,"login":"tiffanyxgu","name":""},"headRefName":"tg-menuitemreview-integration-test","number":129,"title":"tg-Added MenuItemReviewIT integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/129"},{"author":{"id":"MDQ6VXNlcjgwNjE0Mzg1","is_bot":false,"login":"giozucca","name":""},"headRefName":"gl-team03-e2e-Test","number":128,"title":"GL - add team03 e2e test for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/128"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"newh","number":113,"title":"Index Page for UCSBOrganization plus tests and stories #23","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/113"},{"author":{"id":"U_kgDOB96_2w","is_bot":false,"login":"hannuhsu","name":"Hannah Su"},"headRefName":"createpg","number":94,"title":"hs - Create Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-s25/team02-s25-08/pull/94"}]
